/home/kskyj/sparrow4/util/testcode/c/sparrow/prep_files/1.API05.c.i
/home/kskyj/sparrow4/util/testcode/c/sparrow/prep_files/2.API16.c.i
/home/kskyj/sparrow4/util/testcode/c/sparrow/prep_files/3.API20.c.i
/home/kskyj/sparrow4/util/testcode/c/sparrow/prep_files/4.API23.c.i
/home/kskyj/sparrow4/util/testcode/c/sparrow/prep_files/5.API24.c.i
/home/kskyj/sparrow4/util/testcode/c/sparrow/prep_files/6.API25.c.i
/home/kskyj/sparrow4/util/testcode/c/sparrow/prep_files/7.API27.c.i
/home/kskyj/sparrow4/util/testcode/c/sparrow/prep_files/8.API28.c.i
/home/kskyj/sparrow4/util/testcode/c/sparrow/prep_files/9.API29.c.i
/home/kskyj/sparrow4/util/testcode/c/sparrow/prep_files/10.API30.c.i
/home/kskyj/sparrow4/util/testcode/c/sparrow/prep_files/11.API31.c.i
/home/kskyj/sparrow4/util/testcode/c/sparrow/prep_files/12.API32.c.i
/home/kskyj/sparrow4/util/testcode/c/sparrow/prep_files/13.API33.c.i
/home/kskyj/sparrow4/util/testcode/c/sparrow/prep_files/14.API34.c.i
/home/kskyj/sparrow4/util/testcode/c/sparrow/prep_files/15.API35.c.i
/home/kskyj/sparrow4/util/testcode/c/sparrow/prep_files/16.API36.c.i
/home/kskyj/sparrow4/util/testcode/c/sparrow/prep_files/17.API37.c.i
/home/kskyj/sparrow4/util/testcode/c/sparrow/prep_files/18.API38.c.i
/home/kskyj/sparrow4/util/testcode/c/sparrow/prep_files/19.API39.c.i
/home/kskyj/sparrow4/util/testcode/c/sparrow/prep_files/20.API40.c.i
/home/kskyj/sparrow4/util/testcode/c/sparrow/prep_files/21.API41.c.i
/home/kskyj/sparrow4/util/testcode/c/sparrow/prep_files/22.API42.c.i
/home/kskyj/sparrow4/util/testcode/c/sparrow/prep_files/23.API43.c.i
/home/kskyj/sparrow4/util/testcode/c/sparrow/prep_files/24.API44.c.i
/home/kskyj/sparrow4/util/testcode/c/sparrow/prep_files/25.API45.c.i
/home/kskyj/sparrow4/util/testcode/c/sparrow/prep_files/26.API46.c.i
/home/kskyj/sparrow4/util/testcode/c/sparrow/prep_files/27.API47.c.i
/home/kskyj/sparrow4/util/testcode/c/sparrow/prep_files/28.API48.c.i
/home/kskyj/sparrow4/util/testcode/c/sparrow/prep_files/29.API50.c.i
/home/kskyj/sparrow4/util/testcode/c/sparrow/prep_files/30.API51.c.i
/home/kskyj/sparrow4/util/testcode/c/sparrow/prep_files/31.BAD_ARGS.FORBIDDEN.AFTER_CALL.c.i
/home/kskyj/sparrow4/util/testcode/c/sparrow/prep_files/32.BAD_CALL.FORBIDDEN.LIB.PROCESS.c.i
/home/kskyj/sparrow4/util/testcode/c/sparrow/prep_files/33.BAD_CALL.FORBIDDEN.LIB.RESOURCE.c.i
/home/kskyj/sparrow4/util/testcode/c/sparrow/prep_files/34.BAD_CALL.FORBIDDEN.LIB.SIGNAL.c.i
/home/kskyj/sparrow4/util/testcode/c/sparrow/prep_files/35.BAD_CALL.FORBIDDEN.LIB.TEMP.c.i
/home/kskyj/sparrow4/util/testcode/c/sparrow/prep_files/36.BAD_CALL.FORBIDDEN.LIB.TIMER.c.i
/home/kskyj/sparrow4/util/testcode/c/sparrow/prep_files/37.BAD_CALL.FORBIDDEN.LIB.TP.c.i
/home/kskyj/sparrow4/util/testcode/c/sparrow/prep_files/38.BAD_CALL.FORBIDDEN.PARAM.LITERAL.c.i
/home/kskyj/sparrow4/util/testcode/c/sparrow/prep_files/39.BAD_CALL.FORBIDDEN.PARAM.NAME.c.i
/home/kskyj/sparrow4/util/testcode/c/sparrow/prep_files/40.BAD_CALL.FORBIDDEN.PARAM.NUMBER.c.i
/home/kskyj/sparrow4/util/testcode/c/sparrow/prep_files/41.BAD_CALL.FORBIDDEN.PARAM.STRING.c.i
/home/kskyj/sparrow4/util/testcode/c/sparrow/prep_files/42.BAD_CALL.FORBIDDEN.PARAM.c.i
/home/kskyj/sparrow4/util/testcode/c/sparrow/prep_files/43.BAD_CALL.FORBIDDEN.VARARGS.c.i
/home/kskyj/sparrow4/util/testcode/c/sparrow/prep_files/44.BAD_CALL.IMPROPER_VARARGS.c.i
/home/kskyj/sparrow4/util/testcode/c/sparrow/prep_files/45.BAD_CALL.INCORRECT_SIZEOF.MEMCPY.c.i
/home/kskyj/sparrow4/util/testcode/c/sparrow/prep_files/46.BAD_CALL.LIBRARY.MEMORY.c.i
/home/kskyj/sparrow4/util/testcode/c/sparrow/prep_files/47.BAD_CALL.MISSING_CALL_PARAM.EXTENDED.c.i
/home/kskyj/sparrow4/util/testcode/c/sparrow/prep_files/48.BAD_CALL.MISSING_CALL_PARAM.c.i
/home/kskyj/sparrow4/util/testcode/c/sparrow/prep_files/49.BAD_CALL.NOT_ALLOWED.PARAM.NAME.c.i
/home/kskyj/sparrow4/util/testcode/c/sparrow/prep_files/50.BAD_CALL.NOT_ALLOWED.PARAM.STRING.c.i
/home/kskyj/sparrow4/util/testcode/c/sparrow/prep_files/51.BAD_CALL.REQUIRED.ARGS.c.i
/home/kskyj/sparrow4/util/testcode/c/sparrow/prep_files/52.BAD_CALL.REQUIRED.LIB_CALL.c.i
/home/kskyj/sparrow4/util/testcode/c/sparrow/prep_files/53.BAD_CALL.REQUIRED.PARAM.c.i
/home/kskyj/sparrow4/util/testcode/c/sparrow/prep_files/54.BAD_CALL.REQUIRED.PRE_CALL.c.i
/home/kskyj/sparrow4/util/testcode/c/sparrow/prep_files/55.BAD_CALL.REQUIRED.VARARGS.c.i
/home/kskyj/sparrow4/util/testcode/c/sparrow/prep_files/56.BAD_CALL.REQUIRED.WRAPPER.c.i
/home/kskyj/sparrow4/util/testcode/c/sparrow/prep_files/57.BAD_CALL.REQUIRED.c.i
/home/kskyj/sparrow4/util/testcode/c/sparrow/prep_files/58.BAD_CALL.TYPE_MISMATCH.SPRINTF.c.i
/home/kskyj/sparrow4/util/testcode/c/sparrow/prep_files/59.BAD_CALL.TYPE_MISMATCH.STRING.c.i
/home/kskyj/sparrow4/util/testcode/c/sparrow/prep_files/60.BAD_ERROR.INVALID_CODE.c.i
/home/kskyj/sparrow4/util/testcode/c/sparrow/prep_files/61.BAD_ERROR.MISSING_INIT.c.i
/home/kskyj/sparrow4/util/testcode/c/sparrow/prep_files/62.BAD_ERROR.MISSING_RETURN.c.i
/home/kskyj/sparrow4/util/testcode/c/sparrow/prep_files/63.BAD_INCLUDE.DUPLICATED.c.i
/home/kskyj/sparrow4/util/testcode/c/sparrow/prep_files/64.BAD_INCLUDE.FORBIDDEN.c.i
/home/kskyj/sparrow4/util/testcode/c/sparrow/prep_files/65.BAD_INCLUDE.INVALID_PATH.c.i
/home/kskyj/sparrow4/util/testcode/c/sparrow/prep_files/66.BAD_INIT.CHAR_ARRAY.c.i
/home/kskyj/sparrow4/util/testcode/c/sparrow/prep_files/67.BAD_INTEGER_CONST_DEFINITION.c.i
/home/kskyj/sparrow4/util/testcode/c/sparrow/prep_files/68.BAD_MACRO.DANGEROUS_USAGE.c.i
/home/kskyj/sparrow4/util/testcode/c/sparrow/prep_files/69.BAD_MACRO.MISUSE.c.i
/home/kskyj/sparrow4/util/testcode/c/sparrow/prep_files/70.BAD_MACRO.MULTI_STMT_WITHOUT_DO_WHILE.c.i
/home/kskyj/sparrow4/util/testcode/c/sparrow/prep_files/71.BAD_MACRO.REPLACE_SECURE_FUNCTIONS.c.i
/home/kskyj/sparrow4/util/testcode/c/sparrow/prep_files/72.BAD_MALLOC.c.i
/home/kskyj/sparrow4/util/testcode/c/sparrow/prep_files/73.BAD_NAME.VARIABLE.c.i
/home/kskyj/sparrow4/util/testcode/c/sparrow/prep_files/74.BAD_OPERATOR.ASSIGNMENT_IN_COND.c.i
/home/kskyj/sparrow4/util/testcode/c/sparrow/prep_files/75.BAD_OPERATOR.LOGICAL_COMPARISON.c.i
/home/kskyj/sparrow4/util/testcode/c/sparrow/prep_files/76.BAD_PRIVILEGE_RELINQUISHMENT.c.i
/home/kskyj/sparrow4/util/testcode/c/sparrow/prep_files/77.BAD_QUALIFIER.FORBIDDEN.PARAM_PTR.c.i
/home/kskyj/sparrow4/util/testcode/c/sparrow/prep_files/78.BAD_QUALIFIER.FORBIDDEN.c.i
/home/kskyj/sparrow4/util/testcode/c/sparrow/prep_files/79.BAD_QUALIFIER.REQUIRED.PARAM_PTR.c.i
/home/kskyj/sparrow4/util/testcode/c/sparrow/prep_files/80.BAD_STRING_MANAGEMENT.c.i
/home/kskyj/sparrow4/util/testcode/c/sparrow/prep_files/81.BAD_STRUCT_MEMBER_ACCESS.c.i
/home/kskyj/sparrow4/util/testcode/c/sparrow/prep_files/82.CHECK_ALIGNMENT_OF_MEMORY.c.i
/home/kskyj/sparrow4/util/testcode/c/sparrow/prep_files/83.CHROOT_JAIL_WITHOUT_CHANGE_WORK_DIR.c.i
/home/kskyj/sparrow4/util/testcode/c/sparrow/prep_files/84.DOUBLE_LOCK.c.i
/home/kskyj/sparrow4/util/testcode/c/sparrow/prep_files/85.DOUBLE_UNLOCK.c.i
/home/kskyj/sparrow4/util/testcode/c/sparrow/prep_files/86.DO_NOT_ASSUME_ENV.c.i
/home/kskyj/sparrow4/util/testcode/c/sparrow/prep_files/87.DO_NOT_USE_GETLOGIN_IN_MULTI_THREAD.c.i
/home/kskyj/sparrow4/util/testcode/c/sparrow/prep_files/88.DO_NOT_USE_HARD_CODING.USERNAME.c.i
/home/kskyj/sparrow4/util/testcode/c/sparrow/prep_files/89.DO_NOT_USE_SIZEOF_ON_ARRAY_PARAM.c.i
/home/kskyj/sparrow4/util/testcode/c/sparrow/prep_files/90.DO_NOT_USE_SIZEOF_ON_PTR.c.i
/home/kskyj/sparrow4/util/testcode/c/sparrow/prep_files/91.EMPTY_BRANCH.c.i
/home/kskyj/sparrow4/util/testcode/c/sparrow/prep_files/92.ENV04.c.i
/home/kskyj/sparrow4/util/testcode/c/sparrow/prep_files/93.ENV32.c.i
/home/kskyj/sparrow4/util/testcode/c/sparrow/prep_files/94.EXCESSIVE_STACK_DEPTH.c.i
/home/kskyj/sparrow4/util/testcode/c/sparrow/prep_files/95.EXECL_REVEALS_DATA.c.i
/home/kskyj/sparrow4/util/testcode/c/sparrow/prep_files/96.FBD01.c.i
/home/kskyj/sparrow4/util/testcode/c/sparrow/prep_files/97.FBD14.c.i
/home/kskyj/sparrow4/util/testcode/c/sparrow/prep_files/98.FBD15.c.i
/home/kskyj/sparrow4/util/testcode/c/sparrow/prep_files/99.FIO43.c.i
/home/kskyj/sparrow4/util/testcode/c/sparrow/prep_files/100.FORBIDDEN_CALL.BEFORE_CALL.c.i
/home/kskyj/sparrow4/util/testcode/c/sparrow/prep_files/101.FORBIDDEN_CALL.LOOP.c.i
/home/kskyj/sparrow4/util/testcode/c/sparrow/prep_files/102.FUNCTION_DEFINITION_TYPE_MISMATCH.c.i
/home/kskyj/sparrow4/util/testcode/c/sparrow/prep_files/103.IMPROPER_NULL_TERMINATION.c.i
/home/kskyj/sparrow4/util/testcode/c/sparrow/prep_files/104.IMPROPER_RANDOM_USAGE.c.i
/home/kskyj/sparrow4/util/testcode/c/sparrow/prep_files/105.INCONSISTENT_GLOBAL_VARIABLE_TYPE.c.i
/home/kskyj/sparrow4/util/testcode/c/sparrow/prep_files/106.INCONSISTENT_GLOBAL_VARIABLE_TYPE_SECOND.c.i
/home/kskyj/sparrow4/util/testcode/c/sparrow/prep_files/107.INCORRECT_PERMISSION.c.i
/home/kskyj/sparrow4/util/testcode/c/sparrow/prep_files/108.MEM08.c.i
/home/kskyj/sparrow4/util/testcode/c/sparrow/prep_files/109.MIS01.c.i
/home/kskyj/sparrow4/util/testcode/c/sparrow/prep_files/110.MIS03.c.i
/home/kskyj/sparrow4/util/testcode/c/sparrow/prep_files/111.MIS04.c.i
/home/kskyj/sparrow4/util/testcode/c/sparrow/prep_files/112.MIS05.c.i
/home/kskyj/sparrow4/util/testcode/c/sparrow/prep_files/113.MIS06.c.i
/home/kskyj/sparrow4/util/testcode/c/sparrow/prep_files/114.MIS07.c.i
/home/kskyj/sparrow4/util/testcode/c/sparrow/prep_files/115.MIS08.c.i
/home/kskyj/sparrow4/util/testcode/c/sparrow/prep_files/116.MIS09.c.i
/home/kskyj/sparrow4/util/testcode/c/sparrow/prep_files/117.MIS10.c.i
/home/kskyj/sparrow4/util/testcode/c/sparrow/prep_files/118.MIS11.c.i
/home/kskyj/sparrow4/util/testcode/c/sparrow/prep_files/119.MIS14.c.i
/home/kskyj/sparrow4/util/testcode/c/sparrow/prep_files/120.MIS15.c.i
/home/kskyj/sparrow4/util/testcode/c/sparrow/prep_files/121.MIS16.c.i
/home/kskyj/sparrow4/util/testcode/c/sparrow/prep_files/122.MIS17.c.i
/home/kskyj/sparrow4/util/testcode/c/sparrow/prep_files/123.MIS18.c.i
/home/kskyj/sparrow4/util/testcode/c/sparrow/prep_files/124.MIS19.c.i
/home/kskyj/sparrow4/util/testcode/c/sparrow/prep_files/125.MIS20.c.i
/home/kskyj/sparrow4/util/testcode/c/sparrow/prep_files/126.MIS21.c.i
/home/kskyj/sparrow4/util/testcode/c/sparrow/prep_files/127.MIS22.c.i
/home/kskyj/sparrow4/util/testcode/c/sparrow/prep_files/128.MIS23.c.i
/home/kskyj/sparrow4/util/testcode/c/sparrow/prep_files/129.MIS24.c.i
/home/kskyj/sparrow4/util/testcode/c/sparrow/prep_files/130.MISSING_WRAPPER_ON_VARIABLE.c.i
/home/kskyj/sparrow4/util/testcode/c/sparrow/prep_files/131.MSC17.c.i
/home/kskyj/sparrow4/util/testcode/c/sparrow/prep_files/132.MSC32.c.i
/home/kskyj/sparrow4/util/testcode/c/sparrow/prep_files/133.MSC34.c.i
/home/kskyj/sparrow4/util/testcode/c/sparrow/prep_files/134.MULTIPLE_BINDS_TO_SAME_PORT.c.i
/home/kskyj/sparrow4/util/testcode/c/sparrow/prep_files/135.NEGATIVE_FILE_DESCRIPTOR.c.i
/home/kskyj/sparrow4/util/testcode/c/sparrow/prep_files/136.NONEFFECTIVE_FUNCTION_CALL.c.i
/home/kskyj/sparrow4/util/testcode/c/sparrow/prep_files/137.PASSWORD_IN_COMMENT.c.i
/home/kskyj/sparrow4/util/testcode/c/sparrow/prep_files/138.PRE09.c.i
/home/kskyj/sparrow4/util/testcode/c/sparrow/prep_files/139.PREMATURE_THREAD_TERMINATION.c.i
/home/kskyj/sparrow4/util/testcode/c/sparrow/prep_files/140.RACE_CONDITION.c.i
/home/kskyj/sparrow4/util/testcode/c/sparrow/prep_files/141.SECURE_OPUS_COMPLEX.c.i
/home/kskyj/sparrow4/util/testcode/c/sparrow/prep_files/142.SECURITY_DECISION_ON_DNS_LOOKUP.c.i
/home/kskyj/sparrow4/util/testcode/c/sparrow/prep_files/143.SIG30.c.i
/home/kskyj/sparrow4/util/testcode/c/sparrow/prep_files/144.SIG32.c.i
/home/kskyj/sparrow4/util/testcode/c/sparrow/prep_files/145.SIZE_CALCULATION_BAD_COMPARE.c.i
/home/kskyj/sparrow4/util/testcode/c/sparrow/prep_files/146.TOO_MANY_METHODS.c.i
/home/kskyj/sparrow4/util/testcode/c/sparrow/prep_files/147.TRYLOCK_FAIL.c.i
/home/kskyj/sparrow4/util/testcode/c/sparrow/prep_files/148.UCTS-028.c.i
/home/kskyj/sparrow4/util/testcode/c/sparrow/prep_files/149.UCTS-041.c.i
/home/kskyj/sparrow4/util/testcode/c/sparrow/prep_files/150.UCTS-044.c.i
/home/kskyj/sparrow4/util/testcode/c/sparrow/prep_files/151.UNBOUNDED_SOURCE_TO_ARRAY.c.i
/home/kskyj/sparrow4/util/testcode/c/sparrow/prep_files/152.UNCONTROLLED_RECURSION.c.i
/home/kskyj/sparrow4/util/testcode/c/sparrow/prep_files/153.USE_CORRECT_BYTE_ORDERING.c.i
/home/kskyj/sparrow4/util/testcode/c/sparrow/prep_files/154.WEAK_ENCRYPTION.HARDCODED_SALT.c.i
/home/kskyj/sparrow4/util/testcode/c/sparrow/prep_files/155.WEAK_ENCRYPTION.INSUFFICIENT_KEY.c.i
/home/kskyj/sparrow4/util/testcode/c/sparrow/prep_files/156.WEAK_ENCRYPTION.PASSWORD.c.i
/home/kskyj/sparrow4/util/testcode/c/sparrow/prep_files/157.WEAK_ENCRYPTION.RISKY_ALGORITHM.c.i
/home/kskyj/sparrow4/util/testcode/c/sparrow/prep_files/158.WEAK_ENCRYPTION.RSA_PADDING.c.i
/home/kskyj/sparrow4/util/testcode/c/sparrow/prep_files/159.all_sample.c.i
/home/kskyj/sparrow4/util/testcode/c/sparrow/prep_files/160.crulcheck.c.i
/home/kskyj/sparrow4/util/testcode/c/sparrow/prep_files/161.main.c.i
/home/kskyj/sparrow4/util/testcode/c/sparrow/prep_files/162.os_con_imp_int.c.i
/home/kskyj/sparrow4/util/testcode/c/sparrow/prep_files/163.sub.c.i
/home/kskyj/sparrow4/util/testcode/c/sparrow/prep_files/164.target.c.i
/home/kskyj/sparrow4/util/testcode/c/sparrow/prep_files/165.mismatch.cpp.ipp
